@hostname = localhost
@port = 3000
@baseurl = http://{{hostname}}:{{port}}/invoices

###

POST {{baseurl}}  HTTP/1.1
content-type: application/json

{
    "status": "draft",
    "id": "AB3456",
    "createdAt": "2023-09-04",
    "paymentTerms": 1
}

###

POST {{baseurl}} HTTP/1.1
content-type: application/json

{
    "status": "pending",
    "id": "AB3457",
    "createdAt": "2023-09-04",
    "paymentTerms": 1,
    "clientName": "Elton Lobo",
    "clientEmail": "elton.lobo@gmail.com",
    "description": "some description",
    "clientAddress": {
        "street": "some client street",
        "city": "some client city",
        "country": "some client country",
        "postCode": "some client postCode"
    },
    "senderAddress": {
        "street": "some sender street",
        "city": "some sender city",
        "country": "some sender country",
        "postCode": "some sender postCode"
    },
    "items": [
        {
            "name": "some name",
            "price": 12.34,
            "quantity": 12
        }
    ]
}

###

GET {{baseurl}} HTTP/1.1
